### ISSUE TITLE
error on deploy flow with connection manager

### ISSUE THREAD

**Issue by gocamiot** [peterprib/node-red-contrib-connectionmanager#16]
Hey Peter. Im getting error in debug windows on deploy of connection manager. I am using the postgres driver. Please help, I need urget connection management. Cannot seem to find a node that does propper connection management. [RED.events] Deprecated use of "nodes-started" event from "/data/node_modules/node-red-contrib-connectionmanager/connectionManager/get-connection.js:27:20". Use "flows:started" instead." . If I have to mention im using docker version of node-red.

**Comment by peterprib** [comment]
Will fix the problem.  Area changed with latest version of node-red

**Comment by gocamiot** [comment]
Morning.

For sure. Thank you. It is a lovely project! I wait your fix. Regards

Jakes van der Mescht
Inventor: iTesseract
0828880117
***@***.***
www.iTesseract.com<http://www.itesseract.com/>
 LinkedIn Profile<https://www.linkedin.com/in/jakes-van-der-mescht-3bab2b8/>
<https://www.linkedin.com/in/jakes-van-der-mescht-3bab2b8/>

________________________________

**Comment by peterprib** [comment]
should be fixed.  Sorry about delay as I had to fix security issue with workspace and github

**Comment by gocamiot** [comment]
Hey Peter,

Thank you man. I appreciate. I hope it will help with sessions. Running out of connections. lol

Apart from the IOT I have built a trading crypto platform on nodered, using nodered as endpoint to my flutter apps. So the quants trades using nodered as middleware. and it is BUSY! So I hope this helps.

Thanks for coming back.


regards

Jakes van der Mescht
Inventor: iTesseract
0828880117
***@***.***
www.iTesseract.com<http://www.itesseract.com/>
 LinkedIn Profile<https://www.linkedin.com/in/jakes-van-der-mescht-3bab2b8/>
<https://www.linkedin.com/in/jakes-van-der-mescht-3bab2b8/>

________________________________

**Comment by peterprib** [comment]
Did write a crude queue manager for flow that may help not overload flows and tried to co-ordinate different persisted data sources.

**Comment by gocamiot** [comment]
Hey Peter. Pls send email.

Peter can you share this and I can see if I can use? Pls. The Queue manager?

Regards

Jakes van der Mescht
Inventor: iTesseract
0828880117
***@***.***
www.iTesseract.com<http://www.itesseract.com/>
 LinkedIn Profile<https://www.linkedin.com/in/jakes-van-der-mescht-3bab2b8/>
<https://www.linkedin.com/in/jakes-van-der-mescht-3bab2b8/>

________________________________

**Comment by peterprib** [comment]
Hi Jakes

Should find in https://github.com/peterprib/node-red-contrib-queuemanager

Regards

Peter Prib

**Comment by gocamiot** [comment]
Hey Peter,

O man I hope you can help.

When starting my docker container now, it does not want to start, it keeps restarting. On this error from docker start -a
1 Oct 07:46:49 - [info] [Connection Manager:tesseract] new connection tesseract
1 Oct 07:46:49 - [red] Uncaught Exception:
1 Oct 07:46:49 - TypeError: conn.pool.release is not a function
    at getConnection (/data/node_modules/node-red-contrib-connectionmanager/connectionManager/connection-manager.js:467:15)
    at /data/node_modules/node-red-contrib-connectionmanager/connectionManager/connection-manager.js:342:4
    at thisObject.query (/data/node_modules/node-red-contrib-connectionmanager/connectionManager/connection-manager.js:721:64)
    at Query.conn.query (/data/node_modules/node-red-contrib-connectionmanager/connectionManager/connection-manager.js:998:5)
    at Query.handleReadyForQuery (/data/node_modules/pg/lib/query.js:128:10)
    at Connection.<anonymous> (/data/node_modules/pg/lib/client.js:247:19)
    at Connection.emit (events.js:198:13)
    at Socket.<anonymous> (/data/node_modules/pg/lib/connection.js:134:12)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ***@***.*** start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ***@***.*** start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


My bigger issue now is, do you know how to recover a non starting docker of nodered so I can get a copy of my flows out?
Im in serious trouble here.

Regards

Jakes van der Mescht
Inventor: iTesseract
0828880117
***@***.***
www.iTesseract.com<http://www.itesseract.com/>
 LinkedIn Profile<https://www.linkedin.com/in/jakes-van-der-mescht-3bab2b8/>
<https://www.linkedin.com/in/jakes-van-der-mescht-3bab2b8/>

________________________________

**Comment by peterprib** [comment]
There is a way as have been there done that.   Need to think about how I
achieved.

Regards

Peter Prib

**Comment by peterprib** [comment]
If you change lines
/data/node_modules/node-red-contrib-connectionmanager/connectionManager/connection-manager.js:465
to look like

(conn)=>{
if(conn(
conn.pool.release(conn.c,()=>{
conn.pool.connectionTested=true;
done();
},
error
)
else error("null connection")
;


It should get you going.


Regards

Peter Prib

**Comment by peterprib** [comment]
Think I know what caused the error,  I did a little too much tidying
without checking.  Was it a postgres connection?

Regards

Peter Prib

**Comment by gocamiot** [comment]
Yes it was.On 01 Oct 2021 09:12, Peter Prib ***@***.***> wrote:

Think I know what caused the error,  I did a little too much tidying

without checking.  Was it a postgres connection?



Regards



Peter Prib

**Comment by peterprib** [comment]
On docker, it makes it a tad more challenging.

If you stop the database it should make it go into different logic.  This
may be the easiest way to get moving.


Regards

Peter Prib

**Comment by gocamiot** [comment]
Hey Peter,

I will try. Did you fix the nodered version? Im sure more people will run into this.

Jakes van der Mescht
Inventor: iTesseract
0828880117
***@***.***
www.iTesseract.com<http://www.itesseract.com/>
 LinkedIn Profile<https://www.linkedin.com/in/jakes-van-der-mescht-3bab2b8/>
<https://www.linkedin.com/in/jakes-van-der-mescht-3bab2b8/>

________________________________

**Comment by peterprib** [comment]
Hi Jake

Have added a new version which fixes the bug I introduced and handle
failure better.  Took a little longer to fix as I found out that pg had a
bug to latest version of node.js so had to update the dependency list which
then replicated the issue you identified.

Regards

Peter Prib

**Comment by gocamiot** [comment]
Hey Peter,

Many thanks for help and quick respnse. Ill give it a try.

Warm Regards

Jakes van der Mescht
Inventor: iTesseract
0828880117
***@***.***
www.iTesseract.com<http://www.itesseract.com/>
 LinkedIn Profile<https://www.linkedin.com/in/jakes-van-der-mescht-3bab2b8/>
<https://www.linkedin.com/in/jakes-van-der-mescht-3bab2b8/>

________________________________
