### ISSUE TITLE
pg dependency installation question

### ISSUE THREAD

**Issue by namtab00** [peterprib/node-red-contrib-connectionmanager#3]
Hi Peter, I'm using your package in a node-red docker container, for connecting to another pgsql dockerized instance.

The [prerequisite](https://github.com/peterprib/node-red-contrib-connectionmanager#install) of installing the **pg** npm package is problematic, as it needs an extra step of setting up a custom image base on [node-red-docker](https://github.com/node-red/node-red-docker), in which i preinstall the pg package:

``` Dockerfile
FROM nodered/node-red

# monetdb prerequisite no longer necessary as of node-red-contrib-connectionmanager@0.0.2
# RUN npm install monetdb@^1.3.0 pg@^8.2.0

RUN npm install pg@^8.2.0
```

I would very much like to be able to just use the [node-red-docker base docker image](https://hub.docker.com/r/nodered/node-red-docker) and then handle the dependecy as a [project](https://nodered.org/docs/user-guide/projects/) dependency

But when installing pg, I'm facing some issues:
![image](https://user-images.githubusercontent.com/995900/83860077-12d51280-a71f-11ea-8fa2-b7d85ded2ec5.png)

From the log, the installation seems to work just fine:
![image](https://user-images.githubusercontent.com/995900/83860185-39934900-a71f-11ea-9787-da6158c7214c.png)

But the installation is signaled as failed and the dependecy remains in pending install event after a container restart:
![image](https://user-images.githubusercontent.com/995900/83860320-68a9ba80-a71f-11ea-8782-e19d234bebfa.png)

**Q** Do you happen to know why is it that the pg dependency cannnot be simply declared and installed as a project dependency, when projects are enabled ?

I realize that this question is not exactly pertitent to your package, but maybe you have faced some similar issue in other contexts.

**Comment by peterprib** [comment]
Sorry can't help but believe it due to the way node-red handles packages as fenced environments.  May be you could run a "exec" node that runs the npm install -g command.  Should only need to do it once every time you start a new image or take a docker snap for base.

**Comment by namtab00** [comment]
Thank you for the feedback.
