### ISSUE TITLE
Usage question for provided nodes

### ISSUE THREAD

**Issue by namtab00** [peterprib/node-red-contrib-connectionmanager#4]
I'm trying to setup a reusable subflow for running a query against PGSQL, so I'm asking here some clarification questions.

![image](https://user-images.githubusercontent.com/995900/83871797-035ec500-a731-11ea-9ff4-b4ee1d48c5aa.png)

### Q1 regarding node _cm-statement_
Do properties:
- **Connection** 
- **Statement** 

support setting their value via flow/global/env or any JSONata expression ( [$flowContext("aproperty")](https://groups.google.com/d/msg/node-red/QtIVXllCj4s/I00lKyQkCgAJ) ) ?

The node help doesn't specify it:
![image](https://user-images.githubusercontent.com/995900/83870855-428c1680-a72f-11ea-88fc-c13c9d23821e.png)

### Q2 regarding node _cm-statement_
The help says one can use _msg.param_  to set the entire collection of params for the statement; does this mean that via the UI the **Params** collection needs to be left empty ?

### Q3 regarding node _Get Connection_
Same as in Q1, can the **Connection** property be dynamically bound ?

### Q4 regarding node _Release Connections_
This node does not have a **Connection** property, so when having multiple connections configured in a flow, in what way does it determine the connection for which to release connections ? Does it release connections on **all** configured connections ?

Sorry for the issue deluge, but I guess I'm one of the pioneers of usage of your package.
Thanks.

**Comment by peterprib** [comment]
q1: No on  flow/global/env as not sure why needed. If have a good use case will add.  In theory easy to do although more complex if per message.
q2: No it just ignores
q3:  No but if you have a good reason will enhance so this works.  See benefits.
q4: Releases all.  Again could enhance to be selective but don't see a good use case as this could cause UOW issues.  Having said that could understand why one may want to have a connection to log events that aren't rolled back in event of failure.

Have no problems improving if there are applicable use cases.  So if you have a requirement issue for each requirement with reasoning.
