### ISSUE TITLE
Bug on cm-statement with postgresql config, adds "$" behind the query

### ISSUE THREAD

**Issue by jperez-jaumebalmes** [peterprib/node-red-contrib-connectionmanager#5]
Hello @peterprib ,

I was trying your node-red node on Windows 7, Node.js version: 12.16.1 with a postgresql Database, and I detected what I think is a bug. When I was trying a query with Mapping parameters, when I tryed 9 parameters or more, I get an error like that:

"Syntax Error near "$"",

After a search in Postgresql logs i found that:

"INSERT INTO testcm (num,num2,msg,msg2,condicion,timewtz,seguro,test1,test2) VALUES ($1,$2,cast($3 as text),cast($4 as varchar(32)),cast($5 as char(2)),cast($6 as timestamp with time zone),$7,$8,$9)$"

as u can see, it adds a "$" at the end of the query, and it only happens when u put 9 or more parameters

I wish this helps you

**Comment by peterprib** [comment]
Found the issue and have fixed.   Silly mistake in code.
