### ISSUE TITLE
Bug on cm-statement with postgresql config, skips $1 Param

### ISSUE THREAD

**Issue by jperez-jaumebalmes** [peterprib/node-red-contrib-connectionmanager#7]
Hello again @peterprib 

I updated the node version to 0.0.5 and now when I execute any query with parameters, skips $1 and starts in $2 param, here a fragment of postgres log.

cound not determine the type of parameter $1
2020-07-20 09:08:06.858 CEST [8444] SENTENCE:  SELECT * FROM testcm WHERE id = $2 OR id = $3

Thanks again

**Comment by peterprib** [comment]
Should be correct now.  Not sure how I missed this in testing.
