### ISSUE TITLE
Question: Supported statement parameter markers

### ISSUE THREAD

**Issue by mrubli** [peterprib/node-red-contrib-connectionmanager#8]
Are `$n`-style parameters officially supported as parameter markers in statements? (I'm currently using PostgreSQL as a backend but I believe the question applies more broadly.)

The reason I'm asking is that `$1`, `$2`, etc. work fine for unmapped parameter arrays (i.e. when I select `msg.payload` in a _cm-statement_ node's _Parameter Array_ property). However, for mapped properties only `?` seems to be supported and `$n` aren't recognized as parameters:

![questionmark](https://user-images.githubusercontent.com/29906522/90655032-ab395880-e273-11ea-98e9-430ccac69254.png)

Compare that with:

![dollar](https://user-images.githubusercontent.com/29906522/90655026-aa082b80-e273-11ea-86bc-6ca3d9a23622.png)

PS: As I'm getting more familiar with this module I'm hoping to be able to contribute a bit to its documentation. I love the functionality but getting started was a bit time-consuming and involved too much trial-and-error and consulting the unit tests. Please let me know if you're open for PRs that improve the doc.

**Comment by peterprib** [comment]
The scanning of parameter markers for mapping only recognises the ISO standard for dynamic sql.  Under the hood it converts it to the Postgres method which doesn't align.   Other databases will have similar issues like Oracle where form :n is used.
